### ISSUE TITLE
Bootstrap Helper

### ISSUE THREAD

**Issue by jeci-sarl** [Caascad/tf#12]
I think we can add a bootstrap helper to automatically create `terraform.tvars`, `shell.nix`, `.envrc`, `.gitignore`, `tffile`, etc.

This helper could be interactive.

**Comment by eonpatapon** [comment]
I has this idea also the UX could be:

```
cd env.git
tf boostrap -c CONFIGURATION -r TAG
```

We would end up this a directory with the name of the configuration.

Inside we would have:

* terraform.tfvars if there is an example in the configuration
* envrc.EXAMPLE if there is in the configuration
* tfffile generated
* shell.nix generated

**Comment by eonpatapon** [comment]
Myabe the configuration could provide it's `shell.nix`

**Comment by eonpatapon** [comment]
Another cool this that it could do is replace the environment in `tfvars`.

Let's say we have an example `terraform.tfvars` in the configuration like this:
```
zone_name = "#ENVIRONMENT#"
```

`tf bootstrap` could copy this file in `env.git/configuration/` and replace the `#ENVIRONMENT#` like we do in .tf files

**Comment by Benjile** [comment]
> Another cool this that it could do is replace the environment in `tfvars`.
> 
> Let's say we have an example `terraform.tfvars` in the configuration like this:
> 
> ```
> zone_name = "#ENVIRONMENT#"
> ```
> 
> `tf bootstrap` could copy this file in `env.git/configuration/` and replace the `#ENVIRONMENT#` like we do in .tf files

You can already do that since the 1.2.0 release: 
` # add any tf and tfvars files present here to override the downloaded configuration
  cp ./*.tf ./*.tfvars "${TMP_DIR}/configurations/${CONFIGURATION}" &>/dev/null || true

  # environment replacement in every *tf* files
  sed -i "s/#ENVIRONMENT#/${ENVIRONMENT}/g" "${TMP_DIR}"/configurations/"${CONFIGURATION}"/*.tf*
`

**Comment by Benjile** [comment]
> I think we can add a bootstrap helper to automatically create `terraform.tvars`, `shell.nix`, `.envrc`, `.gitignore`, `tffile`, etc.
> 
> This helper could be interactive.

all those file are not currently on the same location in our environment directory, so how can we handle this?

**Comment by Benjile** [comment]
> I think we can add a bootstrap helper to automatically create `terraform.tvars`, `shell.nix`, `.envrc`, `.gitignore`, `tffile`, etc.
> 
> This helper could be interactive.

if we store envrc.EXAMPLE in the lib/configuration/<config> directory the helper can copy this file to .envrc. Is it good for you?

**Comment by eonpatapon** [comment]
I think we can try this way, also it should make replacements of `#ENVIRONMENT#` in it

**Comment by Benjile** [comment]
you mean a replacement in .envrc?

**Comment by eonpatapon** [comment]
Yes, for example in `configurations/keycloak-vault-infra/envrc.EXAMPLE` I would have:
```
export VAULT_ADDR=https://vault.#ENVIRONMENT#.caascad.com
```

When running `tf bootstrap -c keycloak-vault-infra` in some `my-env` git, I would end up with a `.envrc`:
```
export VAULT_ADDR=https://vault.my-env.caascad.com
```

**Comment by Benjile** [comment]
Are we sure we want to substitude #ENVIRONMENT# in terraform.tfvars?
During init apply or run we already copy that file to .tmp/configurations/<config>, and then we apply a sed on any file here.

**Comment by Benjile** [comment]
https://github.com/Caascad/tf/pull/20

**Comment by duthifree** [comment]
Hi,

Is it possible to :

- add `source_up` in  `/lib`  `.envrc` ?

- update `.envrc` comment for personal credentials ?

thx

**Comment by Benjile** [comment]
The bootstrap command should add fe_domain and fe_tenant

**Comment by Benjile** [comment]
#ENVIRONMENT# variable should be replaced in EXAMPLE files also

**Comment by eonpatapon** [comment]
We can close this I guess
