### ISSUE TITLE
Use tf while working locally

### ISSUE THREAD

**Issue by q-b** [Caascad/tf#14]
A flag can be added to `tf` disable the download of modules and configurations. It would allow to edit files directly within the `.tmp` directory for testing.

The current behavior should be kept as default.

**Comment by eonpatapon** [comment]
Or... let the user set a local path in `LIB_URL`

**Comment by Benjile** [comment]
What can be easily done is to skip git operations when TMP_DIR is set by the user.

**Comment by Benjile** [comment]
done with 1.5.0 release
